name: tasks_app
description: "A new Flutter project."
 
publish_to: 'none'  

 
version: 1.0.0+1

environment:
  sdk: ^3.5.4
 
dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.1.2
  api_cache_manager: ^1.0.2
  timezone: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

 
flutter:

 
  uses-material-design: true
 